### ISSUE TITLE
Cannot start `Run Build Task: Run and watch web api`

### ISSUE THREAD

**Issue by ivarref** [bjartnes/bounded-disturbances#13]
```
> Executing task: dotnet watch -p api-under-test/api-under-test.csproj run <

watch : Polling file watcher is enabled
watch : Started
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at api_under_test.Startup.ConfigureServices(IServiceCollection services) in /workspace/api-under-test/Startup.cs:line 67
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at api_under_test.Program.Main(String[] args) in /workspace/api-under-test/Program.cs:line 37
watch : Exited with error code 134
watch : Waiting for a file to change before restarting dotnet..
```

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Thanks, I will try to make this part smoother....

**Comment by haakonmb** [comment]
I got this error when the step `setup logging and dashboard` hadnt been run yet or finished with an error. I assume that the reason this happens is that the steps the user needs to take has an order in the included image, but the list has them out of order. I re-ordered the items and put an explicit order on them in my PR here: https://github.com/bjartnes/bounded-disturbances/pull/14

**Comment by bjartwolf** [comment]
I removed some of the functionality that caused this to fail to simplify
